- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/1"
    job: "/usr/bin/ansible-pull --vault-password-file /opt/ansible_vault/.vault_key  -o -U https://github.com/Sweetmine/ansible_pull.git > /dev/null"
